### PR TITLE
Removing file name numbers

### LINKED ISSUE #11: Remove numbers from before the file names
Each page has a number in the file name that is used to order the pages in the navigation.

It would be nicer to use `nav-display-order: X` in the YML at the top of the page and then `Order-by:nav-display-order` when in the loop. 

Or something like that

### PR DESCRIPTION
**Pull request by mattgreenfield**
Fixes #11 

Removing numbers from the file names, they were being used to order the navigation, this has been replaced by `nav-position:` in the post YML.

The glossary requires sub collections which don't really work so I've made a little hack for that which tidys up the folder structure a lot. 

It should be a lot easier now to restructure the site and make it easier to use as per #19 

@AidanThreadgold @Dayjo

### CODE REVIEW

**Comment by AidanThreadgold** [comment]
Nice!

**Comment by AidanThreadgold** [comment]
Would you be able to update the change log page builder link please :)

**Comment by mattgreenfield** [comment]
Yup, I searched the _glossary and _tutorials folders and missed this one.

**Comment by Dayjo** [comment]
Woo :)

**Pull request merged**
